# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='zmq_test_buffs.proto',
  package='zmq_tests_proto_defs',
  serialized_pb='\n\x14zmq_test_buffs.proto\x12\x14zmq_tests_proto_defs\"\x17\n\x06String\x12\r\n\x05value\x18\x01 \x01(\t\"\x18\n\x07Integer\x12\r\n\x05value\x18\x01 \x01(\x05\"c\n\x03\x42ig\x12,\n\x06string\x18\x01 \x02(\x0b\x32\x1c.zmq_tests_proto_defs.String\x12.\n\x07integer\x18\x02 \x02(\x0b\x32\x1d.zmq_tests_proto_defs.Integer')




_STRING = descriptor.Descriptor(
  name='String',
  full_name='zmq_tests_proto_defs.String',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='zmq_tests_proto_defs.String.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=46,
  serialized_end=69,
)


_INTEGER = descriptor.Descriptor(
  name='Integer',
  full_name='zmq_tests_proto_defs.Integer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='zmq_tests_proto_defs.Integer.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=71,
  serialized_end=95,
)


_BIG = descriptor.Descriptor(
  name='Big',
  full_name='zmq_tests_proto_defs.Big',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='string', full_name='zmq_tests_proto_defs.Big.string', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='integer', full_name='zmq_tests_proto_defs.Big.integer', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=97,
  serialized_end=196,
)

_BIG.fields_by_name['string'].message_type = _STRING
_BIG.fields_by_name['integer'].message_type = _INTEGER
DESCRIPTOR.message_types_by_name['String'] = _STRING
DESCRIPTOR.message_types_by_name['Integer'] = _INTEGER
DESCRIPTOR.message_types_by_name['Big'] = _BIG

class String(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STRING
  
  # @@protoc_insertion_point(class_scope:zmq_tests_proto_defs.String)

class Integer(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INTEGER
  
  # @@protoc_insertion_point(class_scope:zmq_tests_proto_defs.Integer)

class Big(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BIG
  
  # @@protoc_insertion_point(class_scope:zmq_tests_proto_defs.Big)

# @@protoc_insertion_point(module_scope)
